/*
THIS IS AN AUTOGENERATED FILE FROM THE METACOMPILER DO NOT MODIFY!
Metacompiler for "TheBinder" language v0.0.1
*\

#include "binder/expression.h" 

namespace binder::autogen{

class Binary : Expr
{
	Expr* left;
	TOKEN_TYPE operator;
	Expr* right;
};

}// namespace binder::autogen