/*
THIS IS AN AUTOGENERATED FILE FROM THE METACOMPILER DO NOT MODIFY!
Metacompiler for "TheBinder" language v0.0.1
*\

#include "binder/expression.h" 

namespace binder::autogen{

class Binary : Expr
{
public:
	Expr* left;
	TOKEN_TYPE operator;
	Expr* right;
	Expr* accept(Visitor* visitor) override
	{ 
 		visitor->acceptBinary(this);
 		return this;
	};
};

class Grouping : Expr
{
public:
	Expr* expr;
	Expr* accept(Visitor* visitor) override
	{ 
 		visitor->acceptGrouping(this);
 		return this;
	};
};

class Literal : Expr
{
public:
	const char* value;
	Expr* accept(Visitor* visitor) override
	{ 
 		visitor->acceptLiteral(this);
 		return this;
	};
};

class Unary : Expr
{
public:
	TOKEN_TYPE operator;
	Expr* right;
	Expr* accept(Visitor* visitor) override
	{ 
 		visitor->acceptUnary(this);
 		return this;
	};
};


}// namespace binder::autogen